version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      front_net:
        aliases:
          - post_db
          - comment_db
      back_net:
        aliases:
          - post_db
          - comment_db  
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment


volumes:
  post_db:

networks:
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24

